import Head from 'next/head'
import Image from 'next/image'
import About from '../components/about_stories/About'
import Footer from '../components/footer/Footer'
import HeroSection from '../components/hero_section/Hero'
import Liquid_Luxury from '../components/liquidLuxSection/liquidLuxury'
import Daily_Routines from '../components/routine/Daily_routine'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Starbucks Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/asset 4.svg" />
      </Head>

      <div class="h-[90vh] flex flex-col lg:flex-row lg:overflow-y-hidden">

          {/* <!-- Fixed sidebar --> */}
          <div class=" lg:w-[32.9rem] ">

            {/* <!-- Sidebar content --> */}
            <HeroSection />

          </div>

          {/* <!-- Scroll wrapper --> */}
          <div class="flex-1 flex lg:overflow-y-hidden">

              {/* <!-- Scrollable container --> */}
              <div class="flex-1 lg:overflow-y-scroll ">
                {/* <!-- Your content --> */}
                    <Liquid_Luxury />
                    <Daily_Routines />
                    <About /> 
                    <Footer />
              </div>

          </div>
      </div>
    </div>
  )
}
